# Generated by Django 4.2.3 on 2023-07-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('song_app', '0003_alter_songfile_song_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalSongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.ManyToManyField(to='song_app.songfile')),
            ],
        ),
    ]
