# Generated by Django 4.2.3 on 2023-07-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songfile',
            name='song_image_url',
            field=models.URLField(null=True),
        ),
    ]
