# Generated by Django 4.2.3 on 2023-07-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_app', '0002_songfile_song_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songfile',
            name='song_image_url',
            field=models.URLField(),
        ),
    ]
