# Generated by Django 4.2.3 on 2023-08-01 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song_app', '0004_personalsongs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalsongs',
            name='song',
        ),
    ]
