# Generated by Django 4.2.3 on 2023-07-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_app', '0003_alter_songfile_song_image_url'),
        ('auth_app', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='saved_songs',
        ),
        migrations.AddField(
            model_name='authuser',
            name='saved_songs',
            field=models.ManyToManyField(related_name='saved_by_users', to='song_app.songfile'),
        ),
    ]
