# Generated by Django 4.2.3 on 2023-07-28 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_remove_userprofile_saved_songs_authuser_saved_songs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
